
version: 2

models:
  - name: customers
    description: "Customers Table"
    columns:
      - name: first_name
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: last_name
        description: "The last initial of the customer"
        tests:
          - not_null